Web/Auction.Mvc/Controllers/BidsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Models;
using Auction.Mvc.Core;
using Auction.Mvc.Attributes;

namespace Auction.Mvc.Controllers
{
    [Authorize]
    public class BidsController : Controller
    {
        private EfContext ctx = new EfContext();

        // Returns a PartialView with ProductId added to the ViewBag
        public ActionResult Index(Guid ProductId)
        {
            ViewBag.ProductId = ProductId;
            return PartialView();
        }

        // GET: Bids/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bid bid = ctx.Bids.Find(id);
            if (bid == null)
            {
                return HttpNotFound();
            }
            return View(bid);
        }

        // GET: Bids/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sum, ProductId, StartBid")] Bid bid)
        {
            Guid productId = new Guid();
            Guid.TryParse(Request["ProductId"], out productId);

            var activeBids = from p1 in ctx.Bids
                             where p1.ProductId == productId
                             select new BidDto { Id = p1.Id, ProductId = p1.ProductId, BidTime = p1.BidTime, Sum = p1.Sum };
            decimal highBid;

            if (activeBids.Count() == 0) {
                decimal.TryParse(Request["StartBid"], out highBid);
            } else {
                highBid = activeBids.Select(x => x.Sum).Max();
            };
            using (ctx)
            {
                //Determines if the bid sum that was sent is actually higher than the last highest bid and saves the changes to DB.
                if (ctx.Markets.Where(x => x.Id == (ctx.ProductMarket.Where(p => p.ProductId == productId).FirstOrDefault().MarketId)).FirstOrDefault().MarketEnd > DateTime.Now)
                {
                    if (ModelState.IsValid)
                    {              
                        if (bid.Sum > highBid)
                        { 
                            bid.Id = Guid.NewGuid();
                            bid.BidTime = DateTime.Now;
                            bid.ProductId = productId;
                            bid.User = CurrentUser.Login;
                            ctx.Bids.Add(bid);
                            ctx.SaveChanges();
                        }
                    }
                }
                return Redirect(Request.UrlReferrer.ToString());
            }        
        }

        // GET: Bids/Edit/5
        [RestrictedForAdmins]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bid bid = ctx.Bids.Find(id);
            if (bid == null)
            {
                return HttpNotFound();
            }
            return View(bid);
        }

        // POST: Bids/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RestrictedForAdmins]
        public ActionResult Edit([Bind(Include = "Id,Sum,ProductID,BidTime")] Bid bid)
        {
            if (ModelState.IsValid)
            {
                ctx.Entry(bid).State = EntityState.Modified;
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bid);
        }

        // GET: Bids/Delete/5
        [RestrictedForAdmins]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bid bid = ctx.Bids.Find(id);
            if (bid == null)
            {
                return HttpNotFound();
            }

            var bids = new BidDto();

            bids.Id = bid.Id;
            bids.ProductName = ctx.Products.Where(x => x.Id == bid.ProductId).FirstOrDefault().Name;
            bids.Sum = bid.Sum;
            bids.BidTime = bid.BidTime;
            bids.User = bid.User;

            return View(bids);
        }

        // Deletes the bid from DB
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RestrictedForAdmins]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Bid bid = ctx.Bids.Find(id);
            ctx.Bids.Remove(bid);
            ctx.SaveChanges();
            return RedirectToAction("Index","Admin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ctx.Dispose();
            }
            base.Dispose(disposing);
        }


        //Gets the active bids that match the given ProductId and sends Json data for populating the Kendo UI grid.
        public JsonResult GetBids(Guid ProductId)
        {
            var data = new List<BidDto>();

            using (ctx)
            {
                var activeBids = from p1 in ctx.Bids
                                 where p1.ProductId == ProductId
                                 select new BidDto { Id = p1.Id, User = p1.User, ProductId = p1.ProductId, BidTime = p1.BidTime, Sum = p1.Sum };

                data = activeBids.Select(x => new BidDto
                {
                    Id = x.Id,
                    User = x.User,
                    ProductId = ctx.Products.FirstOrDefault(p => p.Id == x.ProductId).Id,
                    BidTime = x.BidTime,
                    Sum = x.Sum
                }).ToList();

                return Json(data, JsonRequestBehavior.AllowGet);
                
            }
        }
    }
}

Web/Auction.Mvc/Controllers/MarketsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Attributes;
using Auction.Mvc.Core;
using FluentScheduler;
using System.Globalization;

namespace Auction.Mvc.Controllers
{
    
    public class MarketsController : Controller
    {
        private EfContext ctx = new EfContext();

         

        // GET: Markets
        public ActionResult Index()
        {

            ViewBag.Admin = CurrentUser.IsAdmin;
            ViewBag.CurrentUser = CurrentUser.FullName;
            return View(ctx.Markets.Where(x => x.MarketStatus == true).ToList());
        }

        // GET: Markets/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Market market = ctx.Markets.Find(id);
            if (market == null)
                return HttpNotFound();

            return View(market);
        }



        // GET: Markets/Create
        [RestrictedForAdmins]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Markets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RestrictedForAdmins]
        public ActionResult Create(FormCollection form)
        {
            //Creates Market object with ID, Name, Type, Start DateTime, End DateTime and Status. 
            //Sets MarketStatus to 1 if DateTime.Now is later than the StartTime, but earlier than the EndTime. 
            //MarketStatus 1 means that the market is active, 0 means it is inactive.
            Market market = new Market();
            market.Id = Guid.NewGuid();
            market.MarketName = Request.Form["MarketName"];

            var marketType = 0;
            if (int.TryParse(Request.Form["MarketType"], out marketType))
            {
                market.MarketType = marketType;
            } else market.MarketType = 1;

            //Custom method concatenates date and time in string formats and returns a DateTime object
            market.MarketStart = ConcatenateDateTime(Request.Form["datePickerStart"], Request.Form["timePickerStart"]);
            market.MarketEnd = ConcatenateDateTime(Request.Form["datePickerEnd"], Request.Form["timePickerEnd"]);


            //Check if given date is later than DateTime.Now. Compares for start time and end time. 
            if (CompareDateTime(market.MarketStart) < 0 && CompareDateTime(market.MarketEnd) > 0)
            {
                market.MarketStatus = true;
            }
            else
            {
                market.MarketStatus = false;
            }

            if (ModelState.IsValid)
            {                
                ctx.Markets.Add(market);
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(market);
        }

        // GET: Markets/Edit/5
        [RestrictedForAdmins]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = ctx.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // POST: Markets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RestrictedForAdmins]
        public ActionResult Edit([Bind(Include = "Id,MarketName,MarketStart,MarketEnd,MarketType,MarketStatus")] Market market)
        {
            if (ModelState.IsValid)
            {
                ctx.Entry(market).State = EntityState.Modified;
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(market);
        }

        // GET: Markets/Delete/5
        [RestrictedForAdmins]
        public ActionResult Delete(Guid? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Market market = ctx.Markets.Find(id);
            if (market == null)
            {
                return HttpNotFound();
            }
            return View(market);
        }

        // POST: Markets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [RestrictedForAdmins]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Market market = ctx.Markets.Find(id);
            if (!ctx.ProductMarket.Any(x => x.MarketId == id))
            {
                ctx.Markets.Remove(market);
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        //Compares a given date against DateTime.Now.
        //Returns a bool value true if given date is later.
        private int CompareDateTime (DateTime time)
        {
            int result = DateTime.Compare(time, DateTime.Now);
            return result;
        }

        //Concatenates two strings and parses them. The parameters given must be a date and a time. 
        //Format for date: YYYY-MM-DD. Format for time: HH:mm 
        private DateTime ConcatenateDateTime (string date, string time)
        {
            var text = date + " " + time;
            string pattern = "dd.MM.yyyy HH:mm";
            var current = new DateTime();
            var result = new DateTime();
            if (DateTime.TryParseExact(text, pattern, null, DateTimeStyles.None, out current))
            {
                result = current;
            }
            else
            {
                result = DateTime.Now;
            }
            return result;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ctx.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Auction.Mvc/Views/Products/Create.cshtml
@model Auction.Mvc.Models.ProductDto

@{
    ViewBag.Title = "Create a new product";
}

@{
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}


@using (Html.BeginForm())
{

<div class="form-horizontal k-content">
    
    <h4>Create a New Auction Item</h4>
    <hr />

    <div class="details-div details-div-col-1 ">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "k-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "k-textbox" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Auction", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MarketsList",null, htmlAttributes: new { @class = "k-item k-input dropdown-list", @Name = "MarketName" })
            </div>
        </div>
        <div class="form-group">
            <span class="control-label col-md-2">Image path</span>
            <div>
                @Html.TextAreaFor(model => model.ImgPath, htmlAttributes: new { @class = "k-textbox", @Name = "ImagePath" })
            </div>
        </div>
    </div>
    <div class="details-div details-div-col-2">
        <div class="form-group">
            @Html.Label("Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriesList",null, htmlAttributes: new { @class = "k-item k-input dropdown-list", @Name = "CategoryName" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartBid, new { htmlAttributes = new { @class = "k-textbox" } })
                @Html.ValidationMessageFor(model => model.StartBid, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Bid Duration", htmlAttributes: new { @class = "k-label col-md-2" })
            <div class="col-md-10">
                <select name="Duration" id="Duration" class="k-item k-input option-list" required>
                    <option value="0">Market</option>
                    <option value="1">1 Day</option>
                    <option value="3">3 Days</option>
                    <option value="5">5 Days</option>
                    <option value="7">7 Days</option>
                    <option value="10">10 Days</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div>
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "k-textbox description-box" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>        
        <br>
</div>
<div class="form-group details-div-col-2">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="k-button k-button" />
    </div>
</div>
}

Web/Auction.Mvc/Views/Products/Destroy.cshtml
@model Auction.Mvc.Models.ProductDto

@{
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}
@{
    ViewBag.Title = "Destroy";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartBid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartBid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bid)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn k-button" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Auction.Mvc/Views/Products/Details.cshtml
@model Auction.Domain.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<script>
    var highBid = '@(ViewBag.HighestBid)';
    var min = parseInt(highBid.substr(0, highBid.length - 3)) + 1;
</script>

<div>
    <h4>Details</h4>
    @Html.ActionLink("Back to List", "Index", "Markets", null, htmlAttributes: new { @class = "k-button" })
    
    @if (CurrentUser.IsAdmin) { 
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class="k-button"})
    }
    <hr />
    <div class="details-div details-div-col-1 picture-div clearfix">
        <img src="/Images/@ViewBag.ImgPath" style="width: 300px; height: 250px;">
    </div>
    <div class="details-div details-div-col-2 ">
        <p>
            <strong>Description:</strong>
        </p>
        <p>
            @if(Model.Description != null) { 
                @Html.DisplayFor(model => model.Description)
            } else
            {
                <span> There is no product description.</span>
            }
        </p>
        <hr />
        <div class="details-div details-div-col-3">
            <strong>Starting Bid:</strong> @Html.DisplayFor(model => model.StartBid)<br />
            <strong>Current Bid:</strong> @(ViewBag.HighestBid) €<br />
            <strong>Time Remaining:</strong> @Html.Raw(ViewBag.RemainingTime) <br />
        </div>
        <div class="details-div details-div-col-4">
            @using (Html.BeginForm("Create","Bids"))
            {
                @Html.AntiForgeryToken()
                <strong>Enter bid: </strong>
                <input id="bidPlacing" name="Sum" class="k-input"/>
                <input id="productId" name="ProductId" type="hidden" value="@Html.DisplayFor(model => model.Id)" />
                <input id="startBid" name="StartBid" type="hidden" value="@Html.DisplayFor(model => model.StartBid)" />
                <input value="Place Bid" type="submit"  class="k-button"/>
            }
        </div>
    </div>   
</div>
<div>
    <div class="bids-div" id="popup">
        @{
            Html.RenderAction("Index", "Bids", new { ProductId = Model.Id });
        }
    </div>
    <div>
        @{ 
            Html.RenderAction("Preview", "Comments", new { ProductId = Model.Id });
        }
    </div>
</div>

<script>
    $("#bidPlacing").kendoNumericTextBox({
        culture: "de-DE",
        min: min,
        max: 999999,
        format: "c2"
    });

</script>

Web/Auction.Mvc/Views/Products/Edit.cshtml
@model Auction.Domain.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal k-content">

        <h4>Edit</h4>
        <hr />

        <div class="details-div details-div-col-1 ">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                Product Name
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "k-textbox" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                Auction
                <div class="col-md-10">
                    @Html.DropDownList("MarketsList", null, htmlAttributes: new { @class = "k-item k-input dropdown-list", @Name = "MarketName" })
                </div>
            </div>
            <div class="form-group">
                <span class="control-label col-md-2">
                    Image path
                </span>
                <div>
                    <input class="k-textbox" id="ImagePath" name="ImagePath" type="text" value="@ViewBag.ImgPath" />
                </div>
            </div>
        </div>
        <div class="details-div details-div-col-2">
            <div class="form-group">
                Category
                <div class="col-md-10">
                    @Html.DropDownList("CategoriesList", null, htmlAttributes: new { @class = "k-item k-input dropdown-list", @Name = "CategoryName" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                Starting Bid
                <div class="col-md-10">
                    @Html.EditorFor(model => model.StartBid, new { htmlAttributes = new { @class = "k-textbox" } })
                    @Html.ValidationMessageFor(model => model.StartBid, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                Bid Duration
                <div class="col-md-10">
                    <select name="Duration" id="Duration" class="k-item k-input option-list" required>
                        <option value="0">Market</option>
                        <option value="1">1 Day</option>
                        <option value="3">3 Days</option>
                        <option value="5">5 Days</option>
                        <option value="7">7 Days</option>
                        <option value="10">10 Days</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div>
                <p class="control-label col-md-2" style="margin-top: 5px;">
                    Description
                </p>
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "k-textbox description-box" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input name="StartTime" type="hidden" value="@Html.DisplayFor(model => model.StartTime)" />
            <input name="EndTime" type="hidden" value="@Html.DisplayFor(model => model.EndTime)" />
            <input type="submit" value="Save" class="btn k-button" /> | @Html.ActionLink("Back to List", "Index", "Admin", null, htmlAttributes: new { @class = "k-button" })

        </div>
    </div>


}

Web/Auction.Mvc/Views/Products/Index.cshtml
@model IEnumerable<Auction.Domain.Market>
@{
    ViewBag.Title = "Products";
    Layout = null;
}
<div data-role="view" data-init="onInit">
    <div id="productsGrid"></div>
</div>
<script>
    var productDataSource = new kendo.data.DataSource({
        transport: {
            read: {
                // the remote service url
                url: function(e){ 
                    return '@Url.Action("GetProducts")' + '?MarketId=' + marketId;
                },
                // the request type
                type: "get",

                // the data type of the returned result
                dataType: "json",

                // additional custom parameters sent to the remote service
                //data: {
                //    lat: 42.42,
                //    lon: 23.20,
                //    cnt: 10
                //}
            },
            update: {
                url: "/Products/Update",
                type: "GET",
                dataType: "json"
            },
        },
    });

    $(document).ready(function () {
        $("#productsGrid").kendoGrid({
            dataSource: productDataSource,
            height: 750,
            groupable: false,
            sortable: true,
            mobile: true,
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            noRecords: true,
            columns: [{
                field: "Name", width: "45%", template: '<a href="/Products/Details/#=Id#" class="k-link grid-link">#=Name#</a>'
            }, {
                field: "Category", width: "125px",
            }, {
                field: "Bid", format: "{0:C}",
            }, {
                field: "StartTime", title: "Starts", template: "#= kendo.toString(kendo.parseDate(StartTime, 'yyyy-MM-dd'), 'dd/MM/yyyy HH:mm') #",
            }, {
                field: "EndTime", title: "Ends", template: "#= kendo.toString(kendo.parseDate(EndTime, 'yyyy-MM-dd'), 'dd/MM/yyyy HH:mm') #",
            }],
            noRecords: {
                template: "Please select a market from the list..."
            },
        });
    });
</script>
@if (CurrentUser.IsAdmin) { 
    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class="k-button"})
    @Html.ActionLink("Edit List", "Index", "Admin", null, htmlAttributes: new { @class = "k-button" })
}

Web/Auction.Mvc/Views/Products/Update.cshtml
@model Auction.Mvc.Models.ProductUpdateDto

@{
    ViewBag.Title = "Update";
}

@{
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<p>
    Update
</p>

@using (Html.BeginForm())
{

    <div class="form-horizontal">
        <h4>Auction Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.StartBid, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}