Web/Auction.Mvc/Controllers/AdminController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Attributes;
using Auction.Mvc.Models;

namespace Auction.Mvc.Controllers
{
    [RestrictedForAdmins]
    public class AdminController : Controller
    {
        private EfContext ctx = new EfContext();

        // GET: ListProducts
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult Products()
        {
            return PartialView("_Products", ctx.Products.ToList());
        }

        public ActionResult Markets()
        {
            return PartialView("_Markets", ctx.Markets.ToList());
        }

        public ActionResult Comments()
        {
            return PartialView("_Comments", ctx.Comments.ToList());
        }

        public ActionResult Bids()
        {
            var bids = ctx.Bids.Select(x => new BidDto {
                Id = x.Id,
                BidTime = x.BidTime,
                ProductName = ctx.Products.Where(p => p.Id == x.ProductId).FirstOrDefault().Name,
                Sum = x.Sum,
                User = x.User
            }).ToList();

            return PartialView("_Bids", bids);
        }

        // GET: ListProducts/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ctx.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: ListProducts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ListProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CategoryId,StartBid,StartTime,Duration,EndTime")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.Id = Guid.NewGuid();
                ctx.Products.Add(product);
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: ListProducts/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ctx.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ListProducts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CategoryId,StartBid,StartTime,Duration,EndTime")] Product product)
        {
            if (ModelState.IsValid)
            {
                ctx.Entry(product).State = EntityState.Modified;
                ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: ListProducts/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ctx.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ListProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Product product = ctx.Products.Find(id);
            ctx.Products.Remove(product);
            ctx.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                ctx.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Auction.Mvc/Controllers/ProductsController.cs
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using Auction.Mvc.Attributes;
using System.Web;
using System.IO;

namespace Auction.Mvc.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        EfContext ctx = new EfContext();


        // GET: Products
        public ActionResult Index(Guid? MarketId)
        {
            return PartialView(MarketId);
        }

        //Method used for getting product data from DB and returns it as JSON for populating the Kendo UI Grid.
        public JsonResult GetProducts(Guid MarketId)
        {
            var data = new List<ProductDto>();

            using (ctx)
            {
                var categories = ctx.Categories.ToList();
                var markets = ctx.Markets.Where(x => x.MarketStatus == true).ToList();
                    //Below only the active products are selected from the total. Active products are considered the ones that are from the selected Market, selected using MarketId.
                var activeProducts = from p1 in ctx.ProductMarket
                                         join p2 in ctx.Products
                                         on p1.ProductId equals p2.Id
                                         where p1.MarketId == MarketId
                                         select new { p2.Id, Name = p2.Name, Description = p2.Description, CategoryId = p2.CategoryId, Bid = p2.StartBid, StartTime = p2.StartTime, Duration = p2.Duration, EndTime = p2.EndTime }; 
                //The active products are projected into a new ProductDto and then returned as JSON.

                data = activeProducts.Select(x => new ProductDto
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    Category = ctx.Categories.FirstOrDefault(c => c.Id == x.CategoryId).Name,
                    Bid = ctx.Bids.Any(b => b.ProductId == x.Id) ? ctx.Bids.OrderByDescending(b => b.Sum).FirstOrDefault(b => b.ProductId == x.Id).Sum : x.Bid,
                    StartTime = x.Duration == 0 ? ctx.Markets.Where(i => i.Id == (ctx.ProductMarket.Where(m => m.ProductId == x.Id).FirstOrDefault().MarketId)).FirstOrDefault().MarketStart : x.StartTime,
                    EndTime = x.Duration == 0 ? ctx.Markets.Where(i => i.Id == (ctx.ProductMarket.Where(m => m.ProductId == x.Id).FirstOrDefault().MarketId)).FirstOrDefault().MarketEnd : x.EndTime
                }).ToList();

                return Json(data, JsonRequestBehavior.AllowGet);
            }
        }
        
        [RestrictedForAdmins]
        public ActionResult Create()
        {
            SelectCategory();
            SelectMarket();

            return View();
        }

        //The following ActionResult receives the data from view in the form of a FormCollection which is then used to populate Product and Market objects with data for creating a new product.
        [HttpPost]
        [RestrictedForAdmins]
        public ActionResult Create(FormCollection form)
        {

            Image image = new Image();
            Product product = new Product();
            //The ProductMarket object is populated here.
            //Fields populated: MarketId, ProductId.
            ProductMarket productMarket = new ProductMarket();
            productMarket.MarketId = SelectMarketId(Request.Form["MarketName"]);
            productMarket.ProductId = product.Id;

            //The Product object is populated here
            //Fields populated: Name, StartBid, Duration, StartTime, EndTime, CategoryId.            
            double days = 0;
            product.Name = Request.Form["Name"];

            if (double.TryParse(Request.Form["Duration"], out days) && days == 0)
            {
                product.StartTime = ctx.Markets
                        .Where(m => m.Id == productMarket.MarketId).FirstOrDefault().MarketStart;
            } else
            {
                product.StartTime = DateTime.Now;
            }


            decimal startBid = 0;
            if (decimal.TryParse(Request.Form["StartBid"], out startBid))
            {
                product.StartBid = startBid;
            } else
            {
                product.StartBid = 0.01M;
            }


            if (double.TryParse(Request.Form["Duration"], out days))
            {
                if(days == 0)
                {
                    product.EndTime = ctx.Markets
                        .Where(m => m.Id == productMarket.MarketId).FirstOrDefault().MarketEnd;
                } 
            }
            else
            {
                product.EndTime = DateTime.Now.AddDays(days);
                product.Duration = days;
            }

            var categoryId = Request.Form["CategoryName"];
            product.CategoryId = SelectCategoryId(categoryId);
            product.Description = WebUtility.HtmlEncode(Request.Form["Description"]);


            //Filepath for the product's image           
            if ((Request.Form["ImagePath"].IndexOfAny(Path.GetInvalidFileNameChars())) != 0)
            {
                image.Path = Request.Form["ImagePath"];
            } else
            {
                image.Path = "default.jpg";
            }
            image.ProductId = product.Id;


            //ModelState is checked to be valid and then objects are sent to be added to the DB.
            if (ModelState.IsValid)
            {
                ctx.Products.Add(product);
                ctx.SaveChanges();

                ctx.Images.Add(image);
                ctx.SaveChanges();
             
                if (ModelState.IsValid)
                {
                    ctx.ProductMarket.Add(productMarket);
                    ctx.SaveChanges();
                    return RedirectToAction("Index","Markets");
                }
            }      
            return View(product);
        }

        //Selects all unique category names that are available and adds them to a new SelectListItem. 
        //Returns a ViewBag item containing the newly created SelectListItem.
        private void SelectCategory()
        {
            List<SelectListItem> itemCategories = new List<SelectListItem>();
            var categories = ctx.Categories.ToList();
            var dataCategories = categories.Select(x => new Category
            {
                Id = x.Id,
                Name = x.Name
            }).ToList();

            foreach (var item in dataCategories.Select(x => x.Id).Distinct())
            {
                itemCategories.Add(new SelectListItem { Text = dataCategories.Where(x => x.Id == item).SingleOrDefault().Name, Value = item.ToString() });
            }
            ViewBag.CategoriesList = itemCategories;
        }

        //Returns a single category ID based on the given name of the category.
        private int SelectCategoryId (string categoryId)
        {
            int value;
            int.TryParse(categoryId, out value); //ctx.Categories.SingleOrDefault(x => x.Name == categoryName).Id;
            return value;
        }

        //Creates a SelectListItem that consists of currently existing Market names and Ids and adds the list into a ViewBag.
        [RestrictedForAdmins]
        private void SelectMarket()
        {
            List<SelectListItem> itemMarkets = new List<SelectListItem>();
            var markets = ctx.Markets.Where(x => x.MarketStatus == false).ToList();
            var dataMarkets = markets.Select(x => new Market
            {
                MarketName = x.MarketName,
                Id = x.Id
            }).ToList();

            foreach (var item in dataMarkets.Select(x => x.Id).Distinct())
            {
                itemMarkets.Add(new SelectListItem { Text = dataMarkets.Where(x => x.Id == item).SingleOrDefault().MarketName, Value = item.ToString() });
            }
            ViewBag.MarketsList = itemMarkets;
        }

        private string SelectPath(Guid id)
        {
            var result = (ctx.Images.Any(x => x.ProductId == id)) && (ctx.Images.Where(x => x.ProductId == id).FirstOrDefault().Path != "") ? ctx.Images.Where(x => x.ProductId == id).FirstOrDefault().Path : "default.jpg";
            return result; 
        }

        //Returns a single market ID based on the given name of the market. 
        private Guid SelectMarketId(string marketId)
        {
            var value = new Guid();
            Guid.TryParse(marketId, out value);
            return  value;
        }

        //Returns Details view for product of the given ID. 

        public ActionResult Details(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = ctx.Products.Find(id);
            var bids = ctx.Bids.Where(b => b.ProductId == id).ToList();            
            if (product == null)
            {
                return HttpNotFound();
            }


            //ViewBag gets populated with Highest Bid and the remaining time of the product.
            ViewBag.RemainingTime = FormatRemainingTime(id);
            ViewBag.HighestBid = bids.Any(b => b.ProductId == id) ? bids.OrderByDescending(b => b.Sum).First(b => b.ProductId == id).Sum : product.StartBid;
            ViewBag.ImgPath = SelectPath(id);


            return View(product);
        }

        //Parse and custom format for TimeSpan. Format: x day(s) y hours and z minutes. 
        private string FormatRemainingTime(Guid id) {
            Product product = ctx.Products.Find(id);
            TimeSpan remainingTime = new TimeSpan();
            if (product.Duration == 0)
            {

Web/Auction.Mvc/Views/Markets/Create.cshtml
@model Auction.Domain.Market

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<script>
    Date.prototype.toDateInputValue = (function () {
        var local = new Date(this);
        local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    });
</script>

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Market</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="details-div details-div-col-1">
            <div class="form-group">
                @Html.Label("Name", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MarketName, new { htmlAttributes = new { @class = "k-textbox" } })
                    @Html.ValidationMessageFor(model => model.MarketName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Type", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MarketType, new { htmlAttributes = new { @class = "k-item k-input dropdown-list" } })
                    @Html.ValidationMessageFor(model => model.MarketType, "", new { @class = "text-danger" })
                </div>
            </div>           
        </div>
        <div class="details-div details-div-col-2">
            <div class="form-group">
                @Html.Label("Start Date", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="col-md-10">
                    <input id="datePickerStart" name="datePickerStart" class = "k-item datepicker option-list" /> 
                    @Html.ValidationMessageFor(model => model.MarketStart, "", new { @class = "text-danger" })
                    <script> 
                        $(document).ready(function () {
                            // create DatePicker from input HTML element
                            $("#datePickerStart").kendoDatePicker();
                        });
                        document.getElementById('datePickerStart').value = new Date().toDateInputValue();
                    </script>
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Start Time", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="k-content">
                    <input id="timePickerStart" value="10:00" name="timePickerStart" />
                </div>
                <script>
                    $(document).ready(function () {
                             // create TimePicker from input HTML element
                        $("#timePickerStart").kendoTimePicker({
                            format: "HH:mm"
                        });
                    });
                </script>
            </div>
            <br />
            <div class="form-group">
                @Html.Label("End Date", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="col-md-10">
                    <input id="datePickerEnd" name="datePickerEnd" class="k-item datepicker option-list" />
                    @Html.ValidationMessageFor(model => model.MarketStart, "", new { @class = "text-danger" })
                    <script>

                        $(document).ready(function () {
                            // create DatePicker from input HTML element
                            $("#datePickerEnd").kendoDatePicker();
                        });
                        document.getElementById('datePickerEnd').value = new Date().toDateInputValue();
                    </script>
                </div>
            </div>
            <div class="form-group">
                @Html.Label("End Time", htmlAttributes: new { @class = "k-label col-md-2" })
                <div class="k-content">
                    <input id="timePickerEnd" value="10:00" name="timePickerEnd"/>
                </div>
                <script>
                    $(document).ready(function () {
                             // create TimePicker from input HTML element
                        $("#timePickerEnd").kendoTimePicker({
                            format: "HH:mm"
                        });
                    });
                </script>
            </div>           
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">             
                <input type="submit" value="Create" class="k-button k-button" />
            </div>
        </div>
    </div>
}
<div>
    <br>
    @Html.ActionLink("Back to List", "Index", "Admin", htmlAttributes: new { @class="k-button"})
</div>

Web/Auction.Mvc/Views/Markets/Delete.cshtml
@model Auction.Domain.Market

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Market</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MarketStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MarketStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MarketStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn k-button" /> |
            @Html.ActionLink("Back to List", "Index", "Admin", htmlAttributes: new { @class="k-button"})
        </div>
    }
</div>

Web/Auction.Mvc/Views/Markets/Details.cshtml
@model Auction.Domain.Market

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Market</h4>
    <hr />
    <table style="width: 500px;">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MarketStart)
            </td>
            <td>
                @Html.DisplayFor(model => model.MarketStart)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MarketEnd)
            </td>

            <td>
                @Html.DisplayFor(model => model.MarketEnd)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MarketType)
            </td>
            <td>
                @Html.DisplayFor(model => model.MarketType)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MarketStatus)
            </td>
            <td>
                @Html.DisplayFor(model => model.MarketStatus)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MarketClosed)
            </td>
            <td>
                @Html.DisplayFor(model => model.MarketClosed)
            </td>
        </tr>
</table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "k-button" }) |
    @Html.ActionLink("Back to List", "Index", "Admin", null, htmlAttributes: new { @class="k-button"})
</p>

Web/Auction.Mvc/Views/Markets/Edit.cshtml
@model Auction.Domain.Market

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Market</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MarketName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MarketStart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketStart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketStart, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MarketEnd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketEnd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketEnd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarketStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketStatus, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MarketClosed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MarketClosed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MarketClosed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn k-button" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Admin", htmlAttributes: new { @class="k-button"})
</div>

Web/Auction.Mvc/Views/Markets/Index - Copy.cshtml
@model IEnumerable<Auction.Domain.Market>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="table-div">
  
     <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MarketStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarketEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarketType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MarketStatus)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MarketStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MarketEnd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MarketType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MarketStatus)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "k=button" }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "k=button" }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "k=button" })
                </td>
            </tr>
        }

    </table>
</div>

Web/Auction.Mvc/Views/Markets/Index.cshtml
@model List<Auction.Domain.Market>

@{
    ViewBag.Title = CurrentUser.FullName;
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}


@section SideBar{
<div class="k-header">
    <p align="center" id="auctions_header"><strong>MARKETS</strong></p>
</div>
@foreach (var item in Model)
{
    <div class="k-button nav-button">
        <a href="Products/GetProducts?MarketId=@Html.DisplayFor(modelItem => item.Id)" onclick="reload('@Html.DisplayFor(modelItem => item.Id)');return false;" class="k-link nav-link">@Html.DisplayFor(modelItem => item.MarketName)</a>
    </div>
}
}


<script>
    var marketId;
    function reload(e) {
        marketId = e;
        $('#productsGrid').data('kendoGrid').dataSource.read();
    }

</script>

@{
    Html.RenderAction("Index", "Products");
}