Web/Auction.Mvc/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Auction.Mvc.Controllers;
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Models;
using Auction.Mvc.Core;
using System.Net;
using System.Text;
using Auction.Mvc.Attributes;
using System.Data.Entity;

namespace Auction.Mvc.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        EfContext ctx = new EfContext();


        public ActionResult Index(Guid productId)
        {

            var data = GetComments(productId);
            ViewBag.ProductId = productId;
            return View(data);
        }

        public ActionResult Login(string login)
        {
            var data = GetComments();
            return View("Index",data);
        }

        public ActionResult Preview(Guid productId)
        {
            var data = GetComments(productId);
            ViewBag.ProductId = productId;
            return PartialView("_Preview", data);
        }

        public ActionResult PreviewUser(string login)
        {
            var data = GetComments();
            return PartialView("_PreviewUser", data);
        }

        // Collects comment data from the form. 
        // Encodes the comment text and then manually decodes <b> and <i> tags so that they can't be properly rendered later on when the comments are displayed.
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Post (FormCollection form)
        {
            StringBuilder sb = new StringBuilder(
                HttpUtility.HtmlEncode(Request.Unvalidated.Form["commentText"].Trim())
                );

            sb.Replace("&lt;b&gt;", "<b>");
            sb.Replace("&lt;/b&gt;", "</b>");
            sb.Replace("&lt;i&gt;", "<i>");
            sb.Replace("&lt;/i&gt;", "</i>");
            var commentText = sb.ToString();

            //Adds the comment data into Comment() object.
            Comment comment = new Comment();
            comment.Id = Guid.NewGuid();
            comment.ProductId = Guid.Parse(Request.Form["productId"]);
            comment.Text = commentText;
            comment.Time = DateTime.Now;
            comment.User = CurrentUser.Login;

            if (ModelState.IsValid)
            {
                ctx.Comments.Add(comment);
                if(comment.Text != "")
                    ctx.SaveChanges();
            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        //Gets the comments according to a given productId
        private List<CommentDto> GetComments(Guid productId)
        {
            var data = ctx.Comments.Where(x => x.ProductId == productId).AsEnumerable().Select(x => new CommentDto
            {
                Id = x.Id,
                ProductId = x.ProductId,
                Text = x.Text,
                User = x.User,
                Time = x.Time
            }).OrderByDescending(x => x.Time).ToList();
            return data;
        }

        //Gets the comments according to the current user
        private List<CommentDto> GetComments()
        {
            var data = ctx.Comments.Where(x => x.User == CurrentUser.Login).AsEnumerable().Select(x => new CommentDto
            {
                Id = x.Id,
                ProductId = x.ProductId,
                Text = x.Text,
                User = x.User,
                Time = x.Time
            }).OrderByDescending(x => x.Time).ToList();
            return data;
        }

        [RestrictedForAdmins]
        public ActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = ctx.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }

            return View(comment);
        }

        [HttpPost, ValidateInput(false)]
        [RestrictedForAdmins]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProductId,Text,User,Time")] Comment comment)
        {
            StringBuilder sb = new StringBuilder(
                HttpUtility.HtmlEncode(comment.Text.Trim()));

            sb.Replace("&lt;b&gt;", "<b>");
            sb.Replace("&lt;/b&gt;", "</b>");
            sb.Replace("&lt;i&gt;", "<i>");
            sb.Replace("&lt;/i&gt;", "</i>");
            var commentText = sb.ToString();

            if (ModelState.IsValid)
            {
                comment.Text = commentText;
                ctx.Entry(comment).State = EntityState.Modified;
                ctx.SaveChanges();
            }
            return RedirectToAction("Index", "Admin");
        }

        public ActionResult Delete(Guid id) {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = ctx.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }

            ctx.Comments.Remove(comment);
            ctx.SaveChanges();

            return RedirectToAction("Index", "Admin");
        }
    }
}

Web/Auction.Mvc/Controllers/UserController.cs
using Auction.Data.Ef;
using Auction.Domain;
using Auction.Mvc.Core;
using Auction.Mvc.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Auction.Mvc.Controllers
{
    public class UserController : Controller
    {
        EfContext ctx = new EfContext();

        // Displays the User profile page. Passes watched, won item and comment counts into the viewbag.
        public ActionResult Index()
        {

            ViewBag.WatchedItem = GetWatchedItems();
            ViewBag.WonItem = GetWonItems();
            ViewBag.Comments = GetCommentCount();
            return View(GetWatchedItems());
        }

        // Renders a partial view with items the user has won
        public ActionResult WonItemsPreview()
        {
            return PartialView("_WonItemsPreview", GetWonItems());
        }


        // Returns the View that displays all of the items user is currently bidding on
        public ActionResult WatchedItems()
        {
            return View(GetWatchedItems());
        }

        // Returns the View that displays all of the items the user has already won
        public ActionResult WonItems()
        {
            return View(GetWonItems());
        }

        // Searches the DB table dbo.COMMENTS for any comments the user has made and returns a Count()
        private int GetCommentCount()
        {
            var results = ctx.Comments.Where(x => x.User == CurrentUser.Login).Count();
            return results;
        }

        // Searches the DB for all items the user has already placed bid on, but still hasn't won yet
        private IEnumerable<UserDto> GetWatchedItems()
        {
            var activeMarkets = ctx.Markets.Where(x => x.MarketStatus == true).Select(x => x.Id).ToList();
            var activeProducts = new List<Guid>();
            var bids = ctx.Bids.Where(x => x.User == CurrentUser.Login).ToList();
            foreach (var item in activeMarkets)
            {
                activeProducts.AddRange(ctx.ProductMarket.Where(x => x.MarketId == item).Select(x => x.ProductId).ToList());
            }

            var watchedBidsAll = bids.OrderByDescending(x => x.Sum).GroupBy(x => x.ProductId).Distinct().Select(x => x.First());
            var watchedBidsOnly = watchedBidsAll.Where(x => x.Winner == false);
            
            var results = GetItems(watchedBidsOnly);

            return results;
        }
        

        // Searches the DB table dbo.BIDS for any bids the user has placed that were the highest bids once the market ended, a.k.a user's won items
        private IEnumerable<UserDto> GetWonItems()
        {
            var wonBids = ctx.Bids.Where(x => (x.User == CurrentUser.Login) && (x.Winner == true)).ToList();
            var results = GetItems(wonBids);
            return results;
        }

        // Returns a UserDto from a given IEnumarable<Bid> object
        private IEnumerable<UserDto> GetItems(IEnumerable<Bid> data)
        {
            var results = data.Select(x => new UserDto
            {
                ProductId = x.ProductId,
                ProductName = ctx.Products.FirstOrDefault(p => p.Id == x.ProductId).Name,
                CategoryName = ctx.Categories.FirstOrDefault(c => c.Id == (ctx.Products.FirstOrDefault(p => p.Id == x.ProductId).CategoryId)).Name,
                CurrentBid = x.Sum
            }).ToList();

            return results;
        }
    }
}

Web/Auction.Mvc/Views/User/Index.cshtml
@model IEnumerable<Auction.Mvc.Models.UserDto>
@{
    ViewBag.Title = CurrentUser.Login;
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}


<div style="max-width: 1150px;">
    <div id="profile-div">
        <div class="details-col-15">
            <img src="~/Images/profile/default.jpg">
        </div>
        <div class="details-div details-col-60">
            <div class="details-div details-height-80">
                <h1 class="text-center">
                    @CurrentUser.FullName
                </h1>
            </div>
            <div class="details-div details-col-100">
                <div class="small-div">
                    <span style="color:red;">
                        (@((ViewBag.WatchedItem as IEnumerable<Auction.Mvc.Models.UserDto>).Count()))
                    </span>
                    @Html.ActionLink("items watching", "WatchedItems", null, htmlAttributes: new { @class = "k-link grid-link" })
                </div>               
                <div class="small-div" >
                    <span style="color:red;">
                        (@((ViewBag.WonItem as IEnumerable<Auction.Mvc.Models.UserDto>).Count()))
                    </span>
                    @Html.ActionLink("items won", "WonItems", null, htmlAttributes: new { @class = "k-link grid-link" })
                </div>
                <div class="small-div">
                    <span style="color:red;">
                        (@(ViewBag.Comments))
                    </span>
                    @Html.ActionLink("your comments", "Login", "Comments", null, htmlAttributes: new { @class = "k-link grid-link" })
                </div>
            </div>
        </div>
    </div>
    <div id="profile-div">
        <div>
            <h2 style="overflow: auto; margin-left: 35px;">Currently bidding: </h2>
        </div>
        <div style="margin-left: 35px; margin-right: 35px;">         
        @if (Model.Count() == 0)
        {
            <p>There are no items yet..</p>
        }
        else
        {
            <table>
                <tr>
                    <th style="width: 50%;">
                        Item
                    </th>
                    <th>
                        Category
                    </th>
                    <th>
                        Current bid
                    </th>
                </tr>
                @{ int i = 0;}
                @foreach (var item in Model)
                {
                <tr class="clickable-row table-row" data-href='/Products/Details/@item.ProductId'>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentBid)
                    </td>
                </tr>
                    i++;
                    if (i == 5) { break; }
                }
            </table>
        }
        </div>
        <div style="margin-right:35px; margin-left:35px;">
            <p style="text-align:right; margin-top: 0px; margin-bottom: 0px;">@Html.ActionLink("View all...", "WatchedItems", null, htmlAttributes: new { @class="k-link grid-link"})</p>
        </div>
    </div>
    @{ 
        Html.RenderAction("WonItemsPreview", "User");
    }
    @{
        Html.RenderAction("PreviewUser", "Comments", CurrentUser.Login);
    }
</div>
    </div>
<script>

    jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });

</script>

Web/Auction.Mvc/Views/User/WatchedItems.cshtml
@model IEnumerable<Auction.Mvc.Models.UserDto>

@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<a class="k-button" href="/User/">Back to profile</a>

@if (Model.Count() == 0)
{
    <p>There are no items yet..</p>
}
else
{
    
    <div style="margin-top: 10px;">
        <table>
            <tr>
                <th>
                    Item 
                </th>
                <th>
                    Category
                </th>
                <th>
                    Current bid
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr class="clickable-row table-row" data-href='/Products/Details/@item.ProductId'>
                    <td >
                        @Html.DisplayFor(model => item.ProductName)
                    </td>
                    <td >
                        @Html.DisplayFor(model => item.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentBid)
                    </td>
                </tr>
            }
        </table>
    </div>
}

<script>

    jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });

</script>

Web/Auction.Mvc/Views/User/WonItems.cshtml
@model IEnumerable<Auction.Mvc.Models.UserDto>

@{
    ViewBag.Title = "Comments";
    Layout = "~/Views/Shared/_CleanLayout.cshtml";
}

<a class="k-button" href="/User/">Back to profile</a>

@if (Model.Count() == 0)
{
    <p>There are no items yet..</p>
}
else
{

    <div style="margin-top: 10px;">
        <table>
            <tr>
                <th>
                    Item
                </th>
                <th>
                    Category
                </th>
                <th>
                    Your bid
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr class="clickable-row table-row" data-href='/Products/Details/@item.ProductId'>
                    <td>
                        @Html.DisplayFor(model => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.CategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CurrentBid)
                    </td>
                </tr>
            }
        </table>
    </div>
}

<script>

    jQuery(document).ready(function ($) {
        $(".clickable-row").click(function () {
            window.location = $(this).data("href");
        });
    });

</script>

Web/Auction.Mvc/Views/User/_WonItemsPreview.cshtml
@model IEnumerable<Auction.Mvc.Models.UserDto>
@{
    Layout = null;
}

<div id="profile-div">
    <div>
        <h2 style="margin-left: 35px;"> Your won items: </h2>
    </div>
    <div style="margin-left: 35px; margin-right: 35px;">
@if (Model.Count() == 0)
{
    <p>There are no items yet..</p>
} else
{
    <table>
        <tr>
            <th>
                Item
            </th>
            <th>
               Category
            </th>
            <th>
                Your bid
            </th>
        </tr>
        @{ int i = 0;}
        @foreach (var item in Model)
        {
            <tr class="clickable-row table-row" data-href='/Products/Details/@item.ProductId'>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CurrentBid)
                </td>
            </tr>
            i++;
            if (i == 5) { break; }
        }
    </table>
}
    </div>
    <div style="margin-right:35px; margin-left:35px;">
        <p style="text-align:right; margin-top: 0px; margin-bottom: 0px;">@Html.ActionLink("View all...", "WonItems", null, htmlAttributes: new { @class = "k-link grid-link" })</p>
    </div>
</div>